---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:

# https://forestry.io/docs/settings/content-sections/
sections:

- # CONTENT --------------------------------------------------------------------
  type: heading
  label: Content

- # POSTS
  type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts

- # PAGES
  type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - default

- # PROJECTS
  type: directory
  label: Projects
  path: _projects
  create: all
  match: "*"
  templates:
  - project

- # DOCUMENTATION
  type: directory
  label: Documentation
  path: _docs
  create: all
  match: "*"
  templates:
  - doc

- # INFO -----------------------------------------------------------------------
  type: heading
  label: Info

- # PEOPLE
  type: directory
  label: People
  path: _people
  create: all
  match: "*"
  templates:
  - person

- # CONTACT INFORMATION
  type: document
  label: Contact Information
  path: _data/information.yml

upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
